export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 30,
      brand: "Nike",
      rating: 4.5,
      numReviews: 60,
    },
    {
      _id: 2,
      name: "Best pants",
      image: "/images/d1.jpg",
      price: 100,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 40,
    },
    {
      _id: 3,
      name: "Fit Shirt",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Blue",
      rating: 2.5,
      numReviews: 30,
    },
    {
      _id: 4,
      name: "Best Shirt",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 5,
      numReviews: 5,
    },
    {
      _id: 5,
      name: "Slim Skirt",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Klein",
      rating: 4.5,
      numReviews: 20,
    },
  ],
};
